# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice
service: serverless-shop

# Configuration variables
custom:
  secrets: ${file(secrets.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  environment:
    STRIPE_SECRET_KEY: ${self:custom.secrets.stripeSecretKey} # Stripe secret API key

# The `functions` block defines what code to deploy
functions:
  createOrder:
    handler: functions/createOrder.handler
    # The `events` block defines how to trigger the handler.createCharge code
    events:
      - http:
          path: orders
          method: post
          cors: true
  createCharge:
    handler: functions/createCharge.handler
    # The `events` block defines how to trigger the handler.createCharge code
    events:
      - http:
          path: charges
          method: post
          cors: true
  fetchProducts:
    handler: functions/fetchProducts.handler
    events:
      - http:
          path: products
          method: get
          cors: true
